[package]
name = "wallet"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
uniffi = { version = "0.28.3", features = [ "cli" ] }
ergo-lib = { version = "0.28.0", features = [ "mnemonic_gen", "compiler", "rest" ] }
